Importing the dependencies

In [113]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

Data Collection and Processing

In [114]:
#loading the dataset to a pandas data frame
sonar_data =pd.read_csv("/content/sonar.csv",header=None)

In [115]:
sonar_data.head()

       0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [116]:
sonar_data.shape  #No of rows and Columns

(208, 61)

In [117]:
sonar_data.describe() #statistical measures of the data
sonar_data[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [118]:
sonar_data.groupby(60).mean()

          0         1         2   ...        57        58        59
60                                ...
M   0.034989  0.045544  0.050720  ...  0.009060  0.008695  0.006930
R   0.022498  0.030303  0.035951  ...  0.006677  0.007078  0.006024

[2 rows x 60 columns]

In [119]:
#seperating labels and data
X=sonar_data.drop(columns=60, axis=1)
Y=sonar_data[60]

Training and Test Data

In [120]:
X_train,x_test,Y_train,y_test=train_test_split(X,Y, test_size=0.15,stratify=Y,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_test = scaler.transform(x_test)

In [121]:
print(X.shape,X_train.shape,x_test.shape)

(208, 60) (176, 60) (32, 60)

Model Training-> Logistic Regression

In [122]:
model = LogisticRegression(max_iter=1000)

In [123]:
#training the model
model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

Model Evaluation

In [124]:
#accuracy on training data
X_train_prediction= model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [125]:
print("Accuracy On Training Data ",training_data_accuracy)

Accuracy On Training Data  0.9147727272727273

In [126]:
#Test Data accuracy
x_test_prediction=model.predict(x_test)
testing_data_accuracy=accuracy_score(x_test_prediction,y_test)

In [127]:
print("Accuracy On Test Data " ,testing_data_accuracy)

Accuracy On Test Data  0.84375

Confusion Matrix

In [128]:
cm = confusion_matrix(y_test, x_test_prediction)
print("Confusion Matrix:\n", cm)

print("Classification Report:\n", classification_report(y_test, x_test_prediction))

Confusion Matrix:
 [[16  1]
 [ 4 11]]
Classification Report:
               precision    recall  f1-score   support

           M       0.80      0.94      0.86        17
           R       0.92      0.73      0.81        15

    accuracy                           0.84        32
   macro avg       0.86      0.84      0.84        32
weighted avg       0.85      0.84      0.84        32

Making a Predictive System

In [129]:
input_data=(0.0201,0.0178,0.0274,0.0232,0.0724,0.0833,0.1232,0.1298,0.2085,0.2720,0.2188,0.3037,0.2959,0.2059,0.0906,0.1610,0.1800,0.2180,0.2026,0.1506,0.0521,0.2143,0.4333,0.5943,0.6926,0.7576,0.8787,0.9060,0.8528,0.9087,0.9657,0.9306,0.7774,0.6643,0.6604,0.6884,0.6938,0.5932,0.5774,0.6223,0.5841,0.4527,0.4911,0.5762,0.5013,0.4042,0.3123,0.2232,0.1085,0.0414,0.0253,0.0131,0.0049,0.0104,0.0102,0.0092,0.0083,0.0020,0.0048,0.0036)
#changing the input data to a numpy array
input_as_array=np.asarray(input_data)
#reshaping the np array as per instance
input_data_reshaped=input_as_array.reshape(1,-1)
input_data_reshaped = scaler.transform(input_data_reshaped)
prediction=model.predict(input_data_reshaped)
print(prediction)

['M']

Printing the Prediction

In [130]:
if prediction[0]=='R':
  print("The object is a Rock")
else:
  print("The object is a Mine")

The object is a Mine